# Generated by Django 5.1.1 on 2024-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
